### ISSUE TITLE
Run folder gets deleted by reboot/clean on linux

### ISSUE THREAD

**Issue by pallas1** [LetheanMovement/lethean-vpn#102]
When installing by deb files, /var/run/lthn folder is created. It works until the system reboots, then the folder is automatically deleted by the system cleaning scripts. Possible solution is creating an empty ".keep" file in the folder, so it doesn't get deleted.

**Comment by ronnylov** [comment]
I tried apply the fix in #167 but it does not work for me.
/var/run/lthn direcory is still removed after a reboot.

**Comment by ronnylov** [comment]
The reason this happens is that /var/run is symlinked to /run directory on debian and /run is tmpfs which is a RAM-disk. So after a reboot it is created from scratch, all old stuff is lost.
In my opinion it is a good choice to have /var/run/lthn on tmpfs because it will avoid potential issues with old pidfiles not removed after sudden reboots. It clears old runtime stuff which is good when booting.

I did my own quick-fix to be able to continue testing. (There may be better ways to fix it, maybe in lthnvpnd itself). Fist I created a script /home/lthn/fixdir.sh

```
#!/bin/bash
mkdir -p /var/log/lthn /var/lib/lthn /var/run/lthn
chown lthn:lthn /var/log/lthn -R
chmod 770 /var/log/lthn
chown lthn:lthn /var/lib/lthn -R
chmod 770 /var/lib/lthn
chown lthn:lthn /var/run/lthn -R
chmod 770 /var/run/lthn
```

Becuase /run is owned by root this script has be run as root. The lethean-vpn-server.service is run as lthn user. So I added this script to /etc/sudoers.d/lthn

```
Cmnd_Alias OPENVPN = /usr/sbin/openvpn
Cmnd_Alias HAPROXY = /usr/sbin/haproxy
Cmnd_Alias FIXDIR = /home/lthn/fixdir.sh

%lthn  ALL=NOPASSWD:OPENVPN,HAPROXY,FIXDIR
```

Then I created my customized lethean-vpn-server.service

```
lthn@pl01:~$ cat /etc/systemd/system/custom-lethean-vpn-server.service 
[Unit]
Description=LTHN VPN server
ConditionPathExists=/usr/bin/lthnvpnd
After=syslog.target

[Service]
EnvironmentFile=/etc/default/lethean-vpn-server
Type=simple
ExecStartPre=/usr/bin/sudo /home/lthn/fixdir.sh
ExecStart=/usr/bin/lthnvpnd $LTHNVPND_ARGS
ExecStopPost=/bin/rm -f /var/run/lthn/lthnvpnd.pid
User=lthn
Restart=always
StandardOutput=syslog
StandardError=syslog
PIDFile=/var/run/lthn/lthnvpnd.pid

[Install]
WantedBy=multi-user.target
```
The ExecStartPre line runs the fixdir.sh script as root by using sudo before lthnvpnd is started.
This quick-fix made lthnvpnd autostart after a reboot.

**Comment by limosek** [comment]
Trying to fix with more sophosticated way https://github.com/LetheanMovement/lethean/tree/feature/limosek/dpkg-status

**Comment by ronnylov** [comment]
Tested with debian package lethean-vpn version 3.1.0-8
The problem is still there. After reboot the directory /var/eun/lthn does not exist.
Getting this error from lthnvpnd:

```
lthn@uk01:~$ lthnvpnd -l DEBUG
INFO:audit:obj=lthnvpnd,type=SERVICE,action=START,
Traceback (most recent call last):
  File "/usr/bin/lthnvpnd", line 182, in <module>
    main(sys.argv[1:])
  File "/usr/bin/lthnvpnd", line 112, in main
    pf = open(config.CONFIG.PIDFILE,"w")
FileNotFoundError: [Errno 2] No such file or directory: '//var/run/lthn/lthnvpnd.pid'
```

**Comment by pallas1** [comment]
the fix on dpkg-status branch seems to be for https://github.com/LetheanMovement/lethean/issues/112 instead

**Comment by ronnylov** [comment]
Tested debian package lethean-vpn version 3.1.0-14
I have no more issues with lethean-vpn-server.service after reboot.
This bug is solved as far as I can see.
