### ISSUE TITLE
Automated install Error: lthnvpnd: error: unrecognized arguments: --upload-sdp

### ISSUE THREAD

**Issue by northriptl** [LetheanMovement/lethean-vpn#39]
Hello

I am trying to use the install script on a fresh ubuntu 18 server, fully updated. I download the script and run it, it runs through most of the code with no errors but then it fails on this:

lthnvpnd: error: unrecognized arguments: --upload-sdp

I think this option was removed and the script needs to be updated.

**Comment by kosztyua** [comment]
I could never make the dispatcher run with ubuntu 18, had to go back to 16. Also, lthnvpnd has many issues now, reported to Lucas, hopefully we get a them solved soon. If you want a working version try 3.0.0.b2 but I would just rather wait until beta testing progresses more.

**Comment by kosztyua** [comment]
On Ubuntu 18 both the init script installation failed and also clients could not connect, maybe due to the HA proxy version. I have played around for a few hours but could not solve it. I would assume Debian 9 must have the same and trying 8 would worth it. 
Eventually on 16 I have first installed with the automatic script, but on other hosts I have customized the script so learnt the manual way too. At current state the script does not make life much easier. If I were to start now without knowing anything, I would open the script to see what it does, but then manually use each line.

**Comment by zib92130** [comment]
As far as I can remember, I've tried to compile previous version of HAProxy (1.7.x) on ubuntu 18 and used it in place of the shipped one. But this didn't worked. Now the causing issue seem to have been corrected since  (https://github.com/LetheanMovement/lethean-vpn/issues/18). I probably need to give another try now things have settled a bit... with the previous LTS versions !

**Comment by kosztyua** [comment]
Definitely will try, setting up new nodes on 16.04 is really not forward looking. Thanks for the info!

**Comment by northriptl** [comment]
I tried on a 16 server and had the same error.

**Comment by kosztyua** [comment]
I think you misunderstood me or didnt read the whole. b3-b4 version does not work, confirmed by multiple providers besides me. Try b2 if you want to try or wait for fix. And if you try b2, you should use ubuntu 16.

**Comment by northriptl** [comment]
oh ok, thanks

**Comment by limosek** [comment]
Sorry for delay. Working on new version. Will commit new changes. But it is really hard to create some generic script for all kind of systems. Working on dockerisation now.

**Comment by limosek** [comment]
should be repaired in latest docker branch 1d7906dd1a4286ce32b090d67aa30de82ea202ad
